from typing import Dict, Any, List
from models.domain import Entity

class ReportGenerator:
    def generate_report(self, entities: List[Entity], links: List[Any], alerts: List[Any]) -> Dict[str, Any]:
        """
        Generates a structured investigation report.
        Distinguishes between FACTS (extracted data) and INFERENCES (AI insights).
        Provides clear provenance.
        """
        high_risk = [e for e in entities if getattr(e, "priorityBand", "") == "HIGH"]
        
        # Build factual summary
        fact_lines = [
            f"**FACT:** Analyzed {len(entities)} total entities across all loaded datasets.",
            f"**FACT:** Identified {len(high_risk)} HIGH risk entities.",
            f"**FACT:** Detected {len(links)} cross-case links."
        ]
        
        # Build inference summary
        inference_lines = []
        if high_risk:
            inference_lines.append("**INFERENCE:** High risk entities warrant immediate review.")
        if links:
            inference_lines.append("**INFERENCE:** Cross-case connections suggest coordinated activity.")
            
        report = {
            "title": "CIRAN Intelligence Report",
            "executive_summary": "Automated network analysis report.",
            "facts": {
                "summary": "\n".join(fact_lines),
                "key_entities": [e.model_dump() for e in high_risk]
            },
            "inferences": {
                "summary": "\n".join(inference_lines) if inference_lines else "No major inferences drawn.",
                "alerts": [a.model_dump() for a in alerts],
                "cross_case_links": [l.model_dump() for l in links]
            },
            "cautions": [
                "Generated by AI Investigation Layer.",
                "Inferences are AI-generated based on correlation logic and must not be treated as proof.",
                "Verify all source records before acting."
            ]
        }
        return report

