from typing import List, Any
from models.domain import CopilotResponse, CopilotTimelineItem, Entity
from services.query_parser import QueryParser
from config.settings import settings

class LLMService:
    def __init__(self):
        self.provider = settings.LLM_PROVIDER
        
    def generate_copilot_response(self, query: str, state: Any, parser: QueryParser) -> CopilotResponse:
        """
        Evidence-Grounded Investigation Engine.
        Deterministic retrieval and response generation simulating RAG.
        """
        intent, extracted_entities = parser.parse_query(query, state.entities)
        
        if not extracted_entities and intent != "UNKNOWN":
            return CopilotResponse(
                summary="Insufficient evidence in the current CIRAN data. Entity or case not found.",
                chips=["Insufficient Evidence"],
                confidence=0,
                caution="Generated by AI. Verify all source records."
            )
            
        if intent == "UNKNOWN":
            return CopilotResponse(
                summary="Query intent not recognized or insufficient parameters provided. Please ask about a specific entity's connections, risk, or timeline.",
                chips=["Unknown Intent"],
                confidence=0,
                caution="Generated by AI. Verify all source records."
            )
            
        ent = extracted_entities[0]
        
        if intent == "ENTITY_CONTEXT":
            neighbors = state.relationship_engine.get_neighbors(ent.id)
            real_neighbors = [n for n in neighbors if n.sourceRecord != "RESOLUTION_ENGINE"]
            ev = list(set([n.sourceRecord for n in real_neighbors]))
            
            return CopilotResponse(
                summary=f"**FACT:** Entity {ent.label} ({ent.id}) is directly connected to {len(real_neighbors)} other entities.\n\n**INFERENCE:** The entity is actively engaged in the network.",
                chips=[ent.label, f"{len(real_neighbors)} Connections"],
                path=[ent.label],
                evidence=ev,
                confidence=85,
                caution="Generated by AI. Verify all source records."
            )
            
        elif intent == "RISK_EXPLANATION":
            factors = ent.priorityFactors or []
            if not factors:
                return CopilotResponse(
                    summary=f"**FACT:** Entity {ent.label} ({ent.id}) has no documented risk factors in the current state.",
                    chips=["No Risk Factors"],
                    confidence=100,
                    caution="Generated by AI. Verify all source records."
                )
                
            summary_lines = [f"**FACT:** Risk score for {ent.label} ({ent.id}) is {ent.priority} ({ent.priorityBand})."]
            ev = []
            
            for f in factors:
                summary_lines.append(f"**DERIVED FINDING:** {f.label} contributes {f.weight} to the risk score.")
                if "fraud" in f.label.lower():
                    summary_lines.append(f"**CAUTION:** A dataset fraud flag alone does not establish criminal activity.")
            
            # Find evidence supporting factors (e.g. PaySim record)
            neighbors = state.relationship_engine.get_neighbors(ent.id)
            ev = list(set([n.sourceRecord for n in neighbors if n.sourceRecord != "RESOLUTION_ENGINE"]))
            
            summary_lines.append(f"\n**INFERENCE:** The entity may warrant further investigation based on documented signals.")
            
            return CopilotResponse(
                summary="\n\n".join(summary_lines),
                chips=[ent.priorityBand, f"Score: {ent.priority}"],
                evidence=ev,
                confidence=90,
                caution="Generated by AI. Verify all source records."
            )
            
        elif intent == "CROSS_CASE_LINK":
            case_links = [l for l in state.cross_case_links if ent.id in l.cases]
            if not case_links:
                return CopilotResponse(
                    summary="**FACT:** No cross-case links detected for this entity.",
                    chips=["No Links"],
                    confidence=100,
                    caution="Generated by AI. Verify all source records."
                )
            
            link = case_links[0]
            return CopilotResponse(
                summary=f"**FACT:** {link.summary}\n\n**DERIVED FINDING:** This cross-case linkage spans {len(link.cases)} cases.",
                chips=["Cross-Case Link Detected"],
                path=link.path,
                evidence=link.evidence,
                confidence=link.confidence,
                caution="Generated by AI. Verify all source records."
            )
            
        elif intent == "TIMELINE":
            # Extract timeline from temporal patterns
            patterns = [p for p in state.patterns if ent.id in p.entities and p.category == "Temporal Burst"]
            if not patterns:
                return CopilotResponse(
                    summary="**FACT:** No significant temporal patterns detected for this entity.",
                    chips=["No Timeline Patterns"],
                    confidence=100,
                    caution="Generated by AI. Verify all source records."
                )
                
            p = patterns[0]
            return CopilotResponse(
                summary=f"**DERIVED FINDING:** {p.title}\n\n**FACT:** {p.why}",
                chips=["Temporal Burst"],
                evidence=p.evidence,
                confidence=p.confidence,
                caution="Generated by AI. Verify all source records."
            )
            
        elif intent == "SUMMARIZE_CASE":
            if ent.type != "case":
                return CopilotResponse(
                    summary=f"**FACT:** Entity {ent.label} is not a case. Cannot summarize.",
                    chips=["Invalid Case"],
                    confidence=100,
                    caution="Generated by AI. Verify all source records."
                )
                
            neighbors = state.relationship_engine.get_neighbors(ent.id)
            ev = list(set([n.sourceRecord for n in neighbors if n.sourceRecord != "RESOLUTION_ENGINE"]))
            
            summary = f"**FACT:** Case {ent.label} contains {len(neighbors)} direct records and entities.\n\n**INFERENCE:** This is an active case profile."
            
            return CopilotResponse(
                summary=summary,
                chips=[ent.label, f"{len(neighbors)} Entities"],
                evidence=ev,
                confidence=85,
                caution="Generated by AI. Verify all source records."
            )

        return CopilotResponse(
            summary="Fallback response.",
            chips=["Fallback"],
            confidence=0,
            caution="Generated by AI. Verify all source records."
        )
