import sys
import os
import json
import logging
from unittest.mock import patch, MagicMock
import httpx

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from config.settings import settings
from api.state import state
from models.domain import ChatMessage, Entity, RetrievalResult, Relation
from api.routes.copilot import CopilotRequest, ask_copilot
from fastapi import HTTPException
from pydantic import ValidationError
from ai.llm_service import LLMService

logging.basicConfig(level=logging.INFO)

def run_tests():
    print("STARTING PHASE 7 SECURITY & AUDIT TESTS\n")
    
    passed = 0
    total = 0
    
    def assert_eq(condition, msg):
        nonlocal passed, total
        total += 1
        if condition:
            passed += 1
            print(f"[PASS] {msg}")
        else:
            print(f"[FAIL] {msg}")

    # 1. Whitespace query rejection
    try:
        req = CopilotRequest(query="   ")
        ask_copilot(req)
        assert_eq(False, "Failed to reject whitespace query")
    except HTTPException as e:
        assert_eq(e.status_code == 400, "Whitespace query rejected correctly")
    except ValidationError:
        assert_eq(True, "Whitespace query rejected by pydantic")

    # 2. Oversized query
    try:
        CopilotRequest(query="A" * 1500)
        assert_eq(False, "Failed to reject oversized query")
    except ValidationError:
        assert_eq(True, "Oversized query rejected (max_length=1000)")

    # 3. Oversized history
    try:
        history = [ChatMessage(role="user", content="A" * 2500)]
        CopilotRequest(query="test", conversation_history=history)
        assert_eq(False, "Failed to reject oversized history content")
    except ValidationError:
        assert_eq(True, "Oversized history content rejected (max_length=2000)")

    # 4. Invalid role
    try:
        history = [ChatMessage(role="hacker", content="test")]
        CopilotRequest(query="test", conversation_history=history)
        assert_eq(False, "Failed to reject invalid role")
    except ValidationError:
        assert_eq(True, "Invalid role 'hacker' rejected")

    # 5. Normal Valid Request & Fallback
    try:
        settings.LLM_PROVIDER = "mock"
        req = CopilotRequest(query="Who is Ravi?")
        res = ask_copilot(req)
        assert_eq(res.summary is not None, "Normal valid request processed safely")
    except Exception as e:
        assert_eq(False, f"Normal request failed: {e}")

    llm = LLMService()
    
    # 6. Fake Evidence ID validation
    result = RetrievalResult(evidence=["EV-123"])
    entities = [Entity(id="E1", label="Test", type="person", subtitle="")]
    ai_data = {
        "answer": "Test.", "facts": [], "derived_findings": [], "limitations": [],
        "evidence_ids": ["EV-123", "EV-FAKE", "RESOLUTION_ENGINE"]
    }
    mapped_res = llm._map_ai_response(ai_data, 90, "ENTITY_CONTEXT", entities, result)
    assert_eq("EV-FAKE" not in mapped_res.evidence, "Fake evidence EV-FAKE completely stripped")
    assert_eq("RESOLUTION_ENGINE" not in mapped_res.evidence, "System evidence RESOLUTION_ENGINE completely stripped")
    assert_eq("EV-123" in mapped_res.evidence, "Valid evidence EV-123 preserved")

    # 7. Retrieval Limits Validation
    from services.copilot_retrieval import CopilotRetrievalService
    ret = CopilotRetrievalService()
    assert_eq(ret.max_depth == 3, "BFS max depth remains 3")
    assert_eq(ret.max_nodes == 50, "Max explored nodes remains 50")

    # 8. Provider Failure Tests
    settings.LLM_API_KEY = "test_key"
    llm.ai_provider.api_key = "test_key"
    
    def simulate_provider_failure(exception_to_raise, desc):
        with patch('httpx.Client.post') as mock_post:
            if isinstance(exception_to_raise, Exception):
                mock_post.side_effect = exception_to_raise
            else:
                mock_resp = MagicMock()
                mock_resp.raise_for_status.side_effect = exception_to_raise
                mock_post.return_value = mock_resp
                
            res = llm.generate_copilot_response("Who is Ravi?", state, state.query_parser, None)
            assert_eq(res.caution == "Generated by AI. Verify all source records.", desc)

    simulate_provider_failure(httpx.TimeoutException("timeout"), "Fallback on provider timeout")
    simulate_provider_failure(httpx.HTTPStatusError("400 Bad Request", request=MagicMock(), response=MagicMock()), "Fallback on HTTP 400")
    simulate_provider_failure(httpx.HTTPStatusError("429 Too Many Requests", request=MagicMock(), response=MagicMock()), "Fallback on HTTP 429")
    simulate_provider_failure(httpx.HTTPStatusError("500 Internal Server Error", request=MagicMock(), response=MagicMock()), "Fallback on HTTP 500")

    # JSON Decode Error
    with patch('httpx.Client.post') as mock_post:
        mock_resp = MagicMock()
        mock_resp.raise_for_status.return_value = None
        mock_resp.json.side_effect = json.JSONDecodeError("Expecting value", "", 0)
        mock_post.return_value = mock_resp
        res = llm.generate_copilot_response("Who is Ravi?", state, state.query_parser, None)
        assert_eq(res.caution == "Generated by AI. Verify all source records.", "Fallback on invalid JSON")

    # Missing API Key
    llm.ai_provider.api_key = ""
    res = llm.generate_copilot_response("Who is Ravi?", state, state.query_parser, None)
    assert_eq(res.caution == "Generated by AI. Verify all source records.", "Fallback on missing API key")

    # 9. Audit Log validation
    with patch('api.routes.copilot.logger.info') as mock_info:
        req = CopilotRequest(query="SUPER_SECRET_QUERY_TEXT")
        ask_copilot(req)
        log_calls = mock_info.call_args_list
        assert_eq(len(log_calls) > 0, "Audit log was written")
        log_msg = log_calls[0][0][0]
        assert_eq("SUPER_SECRET_QUERY_TEXT" not in log_msg, "Audit log does not contain raw query")
        assert_eq("Intent" in log_msg and "Success: True" in log_msg, "Audit log contains safe metadata")

    print(f"\nRESULTS: {passed}/{total} TESTS PASSED")

if __name__ == "__main__":
    run_tests()
