from fastapi import APIRouter
from typing import List
from api.state import state
from models.domain import TimelineEvent

router = APIRouter()

@router.get("", response_model=List[TimelineEvent])
def get_global_timeline():
    # Sort events by timestamp or date if possible, but state.timeline is generated by TemporalAnalysisService
    return state.timeline
