/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as CrossCaseRouteImport } from './routes/cross-case'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EntityResolutionRouteImport } from './routes/entity-resolution'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as EntityIdRouteImport } from './routes/entity/$id'
import { Route as EntityIdIndexRouteImport } from './routes/entity/$id/index'
import { Route as EntityIdNetworkRouteImport } from './routes/entity/$id/network'
import { Route as EntityIdTimelineRouteImport } from './routes/entity/$id/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossCaseRoute = CrossCaseRouteImport.update({
  id: '/cross-case',
  path: '/cross-case',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityResolutionRoute = EntityResolutionRouteImport.update({
  id: '/entity-resolution',
  path: '/entity-resolution',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityIdRoute = EntityIdRouteImport.update({
  id: '/entity/$id',
  path: '/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityIdIndexRoute = EntityIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntityIdRoute,
} as any)
const EntityIdNetworkRoute = EntityIdNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => EntityIdRoute,
} as any)
const EntityIdTimelineRoute = EntityIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => EntityIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/copilot': typeof CopilotRoute
  '/cross-case': typeof CrossCaseRoute
  '/dashboard': typeof DashboardRoute
  '/entity-resolution': typeof EntityResolutionRoute
  '/evidence': typeof EvidenceRoute
  '/investigations': typeof InvestigationsRoute
  '/network': typeof NetworkRoute
  '/patterns': typeof PatternsRoute
  '/timeline': typeof TimelineRoute
  '/entity/$id': typeof EntityIdRouteWithChildren
  '/entity/$id/network': typeof EntityIdNetworkRoute
  '/entity/$id/timeline': typeof EntityIdTimelineRoute
  '/entity/$id/': typeof EntityIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/copilot': typeof CopilotRoute
  '/cross-case': typeof CrossCaseRoute
  '/dashboard': typeof DashboardRoute
  '/entity-resolution': typeof EntityResolutionRoute
  '/evidence': typeof EvidenceRoute
  '/investigations': typeof InvestigationsRoute
  '/network': typeof NetworkRoute
  '/patterns': typeof PatternsRoute
  '/timeline': typeof TimelineRoute
  '/entity/$id/network': typeof EntityIdNetworkRoute
  '/entity/$id/timeline': typeof EntityIdTimelineRoute
  '/entity/$id': typeof EntityIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/copilot': typeof CopilotRoute
  '/cross-case': typeof CrossCaseRoute
  '/dashboard': typeof DashboardRoute
  '/entity-resolution': typeof EntityResolutionRoute
  '/evidence': typeof EvidenceRoute
  '/investigations': typeof InvestigationsRoute
  '/network': typeof NetworkRoute
  '/patterns': typeof PatternsRoute
  '/timeline': typeof TimelineRoute
  '/entity/$id': typeof EntityIdRouteWithChildren
  '/entity/$id/network': typeof EntityIdNetworkRoute
  '/entity/$id/timeline': typeof EntityIdTimelineRoute
  '/entity/$id/': typeof EntityIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/copilot'
    | '/cross-case'
    | '/dashboard'
    | '/entity-resolution'
    | '/evidence'
    | '/investigations'
    | '/network'
    | '/patterns'
    | '/timeline'
    | '/entity/$id'
    | '/entity/$id/network'
    | '/entity/$id/timeline'
    | '/entity/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/copilot'
    | '/cross-case'
    | '/dashboard'
    | '/entity-resolution'
    | '/evidence'
    | '/investigations'
    | '/network'
    | '/patterns'
    | '/timeline'
    | '/entity/$id/network'
    | '/entity/$id/timeline'
    | '/entity/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/copilot'
    | '/cross-case'
    | '/dashboard'
    | '/entity-resolution'
    | '/evidence'
    | '/investigations'
    | '/network'
    | '/patterns'
    | '/timeline'
    | '/entity/$id'
    | '/entity/$id/network'
    | '/entity/$id/timeline'
    | '/entity/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CopilotRoute: typeof CopilotRoute
  CrossCaseRoute: typeof CrossCaseRoute
  DashboardRoute: typeof DashboardRoute
  EntityResolutionRoute: typeof EntityResolutionRoute
  EvidenceRoute: typeof EvidenceRoute
  InvestigationsRoute: typeof InvestigationsRoute
  NetworkRoute: typeof NetworkRoute
  PatternsRoute: typeof PatternsRoute
  TimelineRoute: typeof TimelineRoute
  EntityIdRoute: typeof EntityIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-case': {
      id: '/cross-case'
      path: '/cross-case'
      fullPath: '/cross-case'
      preLoaderRoute: typeof CrossCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity-resolution': {
      id: '/entity-resolution'
      path: '/entity-resolution'
      fullPath: '/entity-resolution'
      preLoaderRoute: typeof EntityResolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/$id': {
      id: '/entity/$id'
      path: '/entity/$id'
      fullPath: '/entity/$id'
      preLoaderRoute: typeof EntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/$id/': {
      id: '/entity/$id/'
      path: '/'
      fullPath: '/entity/$id/'
      preLoaderRoute: typeof EntityIdIndexRouteImport
      parentRoute: typeof EntityIdRoute
    }
    '/entity/$id/network': {
      id: '/entity/$id/network'
      path: '/network'
      fullPath: '/entity/$id/network'
      preLoaderRoute: typeof EntityIdNetworkRouteImport
      parentRoute: typeof EntityIdRoute
    }
    '/entity/$id/timeline': {
      id: '/entity/$id/timeline'
      path: '/timeline'
      fullPath: '/entity/$id/timeline'
      preLoaderRoute: typeof EntityIdTimelineRouteImport
      parentRoute: typeof EntityIdRoute
    }
  }
}

interface EntityIdRouteChildren {
  EntityIdNetworkRoute: typeof EntityIdNetworkRoute
  EntityIdTimelineRoute: typeof EntityIdTimelineRoute
  EntityIdIndexRoute: typeof EntityIdIndexRoute
}

const EntityIdRouteChildren: EntityIdRouteChildren = {
  EntityIdNetworkRoute: EntityIdNetworkRoute,
  EntityIdTimelineRoute: EntityIdTimelineRoute,
  EntityIdIndexRoute: EntityIdIndexRoute,
}

const EntityIdRouteWithChildren = EntityIdRoute._addFileChildren(
  EntityIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CopilotRoute: CopilotRoute,
  CrossCaseRoute: CrossCaseRoute,
  DashboardRoute: DashboardRoute,
  EntityResolutionRoute: EntityResolutionRoute,
  EvidenceRoute: EvidenceRoute,
  InvestigationsRoute: InvestigationsRoute,
  NetworkRoute: NetworkRoute,
  PatternsRoute: PatternsRoute,
  TimelineRoute: TimelineRoute,
  EntityIdRoute: EntityIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
